# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_star_tracker')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_star_tracker')
    _star_tracker = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_star_tracker', [dirname(__file__)])
        except ImportError:
            import _star_tracker
            return _star_tracker
        if fp is not None:
            try:
                _mod = imp.load_module('_star_tracker', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _star_tracker = swig_import_helper()
    del swig_import_helper
else:
    import _star_tracker
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _star_tracker.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _star_tracker.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _star_tracker.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _star_tracker.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _star_tracker.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _star_tracker.SwigPyIterator_equal(self, x)

    def copy(self):
        return _star_tracker.SwigPyIterator_copy(self)

    def next(self):
        return _star_tracker.SwigPyIterator_next(self)

    def __next__(self):
        return _star_tracker.SwigPyIterator___next__(self)

    def previous(self):
        return _star_tracker.SwigPyIterator_previous(self)

    def advance(self, n):
        return _star_tracker.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _star_tracker.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _star_tracker.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _star_tracker.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _star_tracker.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _star_tracker.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _star_tracker.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _star_tracker.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)


def new_doubleArray(nelements):
    return _star_tracker.new_doubleArray(nelements)
new_doubleArray = _star_tracker.new_doubleArray

def delete_doubleArray(ary):
    return _star_tracker.delete_doubleArray(ary)
delete_doubleArray = _star_tracker.delete_doubleArray

def doubleArray_getitem(ary, index):
    return _star_tracker.doubleArray_getitem(ary, index)
doubleArray_getitem = _star_tracker.doubleArray_getitem

def doubleArray_setitem(ary, index, value):
    return _star_tracker.doubleArray_setitem(ary, index, value)
doubleArray_setitem = _star_tracker.doubleArray_setitem

def new_longArray(nelements):
    return _star_tracker.new_longArray(nelements)
new_longArray = _star_tracker.new_longArray

def delete_longArray(ary):
    return _star_tracker.delete_longArray(ary)
delete_longArray = _star_tracker.delete_longArray

def longArray_getitem(ary, index):
    return _star_tracker.longArray_getitem(ary, index)
longArray_getitem = _star_tracker.longArray_getitem

def longArray_setitem(ary, index, value):
    return _star_tracker.longArray_setitem(ary, index, value)
longArray_setitem = _star_tracker.longArray_setitem

def new_intArray(nelements):
    return _star_tracker.new_intArray(nelements)
new_intArray = _star_tracker.new_intArray

def delete_intArray(ary):
    return _star_tracker.delete_intArray(ary)
delete_intArray = _star_tracker.delete_intArray

def intArray_getitem(ary, index):
    return _star_tracker.intArray_getitem(ary, index)
intArray_getitem = _star_tracker.intArray_getitem

def intArray_setitem(ary, index, value):
    return _star_tracker.intArray_setitem(ary, index, value)
intArray_setitem = _star_tracker.intArray_setitem

def new_shortArray(nelements):
    return _star_tracker.new_shortArray(nelements)
new_shortArray = _star_tracker.new_shortArray

def delete_shortArray(ary):
    return _star_tracker.delete_shortArray(ary)
delete_shortArray = _star_tracker.delete_shortArray

def shortArray_getitem(ary, index):
    return _star_tracker.shortArray_getitem(ary, index)
shortArray_getitem = _star_tracker.shortArray_getitem

def shortArray_setitem(ary, index, value):
    return _star_tracker.shortArray_setitem(ary, index, value)
shortArray_setitem = _star_tracker.shortArray_setitem


def getStructSize(self):
    try:
        return eval('sizeof_' + repr(self).split(';')[0].split('.')[-1])
    except (NameError) as e:
        typeString = 'sizeof_' + repr(self).split(';')[0].split('.')[-1]
        raise NameError(e.message + '\nYou tried to get this size macro: ' + typeString + 
            '\n It appears to be undefined.  \nYou need to run the SWIG GEN_SIZEOF' +  
            ' SWIG macro against the class/struct in your SWIG file if you want to ' + 
            ' make this call.\n')


def protectSetAttr(self, name, value):
    if(hasattr(self, name) or name == 'this'):
        object.__setattr__(self, name, value)
    else:
        raise ValueError('You tried to add this variable: ' + name + '\n' + 
            'To this class: ' + str(self))

def protectAllClasses(moduleType):
    import inspect
    clsmembers = inspect.getmembers(sys.modules[__name__], inspect.isclass)
    for member in clsmembers:
        try:
            exec(str(member[0]) + '.__setattr__ = protectSetAttr')
            exec(str(member[0]) + '.getStructSize = getStructSize') 
        except (AttributeError, TypeError) as e:
            pass



def new_boolArray(nelements):
    return _star_tracker.new_boolArray(nelements)
new_boolArray = _star_tracker.new_boolArray

def delete_boolArray(ary):
    return _star_tracker.delete_boolArray(ary)
delete_boolArray = _star_tracker.delete_boolArray

def boolArray_getitem(ary, index):
    return _star_tracker.boolArray_getitem(ary, index)
boolArray_getitem = _star_tracker.boolArray_getitem

def boolArray_setitem(ary, index, value):
    return _star_tracker.boolArray_setitem(ary, index, value)
boolArray_setitem = _star_tracker.boolArray_setitem
class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _star_tracker.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _star_tracker.IntVector___nonzero__(self)

    def __bool__(self):
        return _star_tracker.IntVector___bool__(self)

    def __len__(self):
        return _star_tracker.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _star_tracker.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _star_tracker.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _star_tracker.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _star_tracker.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _star_tracker.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _star_tracker.IntVector___setitem__(self, *args)

    def pop(self):
        return _star_tracker.IntVector_pop(self)

    def append(self, x):
        return _star_tracker.IntVector_append(self, x)

    def empty(self):
        return _star_tracker.IntVector_empty(self)

    def size(self):
        return _star_tracker.IntVector_size(self)

    def swap(self, v):
        return _star_tracker.IntVector_swap(self, v)

    def begin(self):
        return _star_tracker.IntVector_begin(self)

    def end(self):
        return _star_tracker.IntVector_end(self)

    def rbegin(self):
        return _star_tracker.IntVector_rbegin(self)

    def rend(self):
        return _star_tracker.IntVector_rend(self)

    def clear(self):
        return _star_tracker.IntVector_clear(self)

    def get_allocator(self):
        return _star_tracker.IntVector_get_allocator(self)

    def pop_back(self):
        return _star_tracker.IntVector_pop_back(self)

    def erase(self, *args):
        return _star_tracker.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _star_tracker.new_IntVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _star_tracker.IntVector_push_back(self, x)

    def front(self):
        return _star_tracker.IntVector_front(self)

    def back(self):
        return _star_tracker.IntVector_back(self)

    def assign(self, n, x):
        return _star_tracker.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _star_tracker.IntVector_resize(self, *args)

    def insert(self, *args):
        return _star_tracker.IntVector_insert(self, *args)

    def reserve(self, n):
        return _star_tracker.IntVector_reserve(self, n)

    def capacity(self):
        return _star_tracker.IntVector_capacity(self)
    __swig_destroy__ = _star_tracker.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _star_tracker.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _star_tracker.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _star_tracker.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _star_tracker.DoubleVector___bool__(self)

    def __len__(self):
        return _star_tracker.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _star_tracker.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _star_tracker.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _star_tracker.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _star_tracker.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _star_tracker.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _star_tracker.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _star_tracker.DoubleVector_pop(self)

    def append(self, x):
        return _star_tracker.DoubleVector_append(self, x)

    def empty(self):
        return _star_tracker.DoubleVector_empty(self)

    def size(self):
        return _star_tracker.DoubleVector_size(self)

    def swap(self, v):
        return _star_tracker.DoubleVector_swap(self, v)

    def begin(self):
        return _star_tracker.DoubleVector_begin(self)

    def end(self):
        return _star_tracker.DoubleVector_end(self)

    def rbegin(self):
        return _star_tracker.DoubleVector_rbegin(self)

    def rend(self):
        return _star_tracker.DoubleVector_rend(self)

    def clear(self):
        return _star_tracker.DoubleVector_clear(self)

    def get_allocator(self):
        return _star_tracker.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _star_tracker.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _star_tracker.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        this = _star_tracker.new_DoubleVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _star_tracker.DoubleVector_push_back(self, x)

    def front(self):
        return _star_tracker.DoubleVector_front(self)

    def back(self):
        return _star_tracker.DoubleVector_back(self)

    def assign(self, n, x):
        return _star_tracker.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _star_tracker.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _star_tracker.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _star_tracker.DoubleVector_reserve(self, n)

    def capacity(self):
        return _star_tracker.DoubleVector_capacity(self)
    __swig_destroy__ = _star_tracker.delete_DoubleVector
    __del__ = lambda self: None
DoubleVector_swigregister = _star_tracker.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _star_tracker.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _star_tracker.StringVector___nonzero__(self)

    def __bool__(self):
        return _star_tracker.StringVector___bool__(self)

    def __len__(self):
        return _star_tracker.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _star_tracker.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _star_tracker.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _star_tracker.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _star_tracker.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _star_tracker.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _star_tracker.StringVector___setitem__(self, *args)

    def pop(self):
        return _star_tracker.StringVector_pop(self)

    def append(self, x):
        return _star_tracker.StringVector_append(self, x)

    def empty(self):
        return _star_tracker.StringVector_empty(self)

    def size(self):
        return _star_tracker.StringVector_size(self)

    def swap(self, v):
        return _star_tracker.StringVector_swap(self, v)

    def begin(self):
        return _star_tracker.StringVector_begin(self)

    def end(self):
        return _star_tracker.StringVector_end(self)

    def rbegin(self):
        return _star_tracker.StringVector_rbegin(self)

    def rend(self):
        return _star_tracker.StringVector_rend(self)

    def clear(self):
        return _star_tracker.StringVector_clear(self)

    def get_allocator(self):
        return _star_tracker.StringVector_get_allocator(self)

    def pop_back(self):
        return _star_tracker.StringVector_pop_back(self)

    def erase(self, *args):
        return _star_tracker.StringVector_erase(self, *args)

    def __init__(self, *args):
        this = _star_tracker.new_StringVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _star_tracker.StringVector_push_back(self, x)

    def front(self):
        return _star_tracker.StringVector_front(self)

    def back(self):
        return _star_tracker.StringVector_back(self)

    def assign(self, n, x):
        return _star_tracker.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _star_tracker.StringVector_resize(self, *args)

    def insert(self, *args):
        return _star_tracker.StringVector_insert(self, *args)

    def reserve(self, n):
        return _star_tracker.StringVector_reserve(self, n)

    def capacity(self):
        return _star_tracker.StringVector_capacity(self)
    __swig_destroy__ = _star_tracker.delete_StringVector
    __del__ = lambda self: None
StringVector_swigregister = _star_tracker.StringVector_swigregister
StringVector_swigregister(StringVector)

class StringSet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringSet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringSet, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _star_tracker.StringSet_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _star_tracker.StringSet___nonzero__(self)

    def __bool__(self):
        return _star_tracker.StringSet___bool__(self)

    def __len__(self):
        return _star_tracker.StringSet___len__(self)

    def append(self, x):
        return _star_tracker.StringSet_append(self, x)

    def __contains__(self, x):
        return _star_tracker.StringSet___contains__(self, x)

    def __getitem__(self, i):
        return _star_tracker.StringSet___getitem__(self, i)

    def add(self, x):
        return _star_tracker.StringSet_add(self, x)

    def discard(self, x):
        return _star_tracker.StringSet_discard(self, x)

    def __init__(self, *args):
        this = _star_tracker.new_StringSet(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def empty(self):
        return _star_tracker.StringSet_empty(self)

    def size(self):
        return _star_tracker.StringSet_size(self)

    def clear(self):
        return _star_tracker.StringSet_clear(self)

    def swap(self, v):
        return _star_tracker.StringSet_swap(self, v)

    def count(self, x):
        return _star_tracker.StringSet_count(self, x)

    def begin(self):
        return _star_tracker.StringSet_begin(self)

    def end(self):
        return _star_tracker.StringSet_end(self)

    def rbegin(self):
        return _star_tracker.StringSet_rbegin(self)

    def rend(self):
        return _star_tracker.StringSet_rend(self)

    def erase(self, *args):
        return _star_tracker.StringSet_erase(self, *args)

    def find(self, x):
        return _star_tracker.StringSet_find(self, x)

    def lower_bound(self, x):
        return _star_tracker.StringSet_lower_bound(self, x)

    def upper_bound(self, x):
        return _star_tracker.StringSet_upper_bound(self, x)

    def equal_range(self, x):
        return _star_tracker.StringSet_equal_range(self, x)

    def insert(self, __x):
        return _star_tracker.StringSet_insert(self, __x)
    __swig_destroy__ = _star_tracker.delete_StringSet
    __del__ = lambda self: None
StringSet_swigregister = _star_tracker.StringSet_swigregister
StringSet_swigregister(StringSet)

class intSet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, intSet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, intSet, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _star_tracker.intSet_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _star_tracker.intSet___nonzero__(self)

    def __bool__(self):
        return _star_tracker.intSet___bool__(self)

    def __len__(self):
        return _star_tracker.intSet___len__(self)

    def append(self, x):
        return _star_tracker.intSet_append(self, x)

    def __contains__(self, x):
        return _star_tracker.intSet___contains__(self, x)

    def __getitem__(self, i):
        return _star_tracker.intSet___getitem__(self, i)

    def add(self, x):
        return _star_tracker.intSet_add(self, x)

    def discard(self, x):
        return _star_tracker.intSet_discard(self, x)

    def __init__(self, *args):
        this = _star_tracker.new_intSet(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def empty(self):
        return _star_tracker.intSet_empty(self)

    def size(self):
        return _star_tracker.intSet_size(self)

    def clear(self):
        return _star_tracker.intSet_clear(self)

    def swap(self, v):
        return _star_tracker.intSet_swap(self, v)

    def count(self, x):
        return _star_tracker.intSet_count(self, x)

    def begin(self):
        return _star_tracker.intSet_begin(self)

    def end(self):
        return _star_tracker.intSet_end(self)

    def rbegin(self):
        return _star_tracker.intSet_rbegin(self)

    def rend(self):
        return _star_tracker.intSet_rend(self)

    def erase(self, *args):
        return _star_tracker.intSet_erase(self, *args)

    def find(self, x):
        return _star_tracker.intSet_find(self, x)

    def lower_bound(self, x):
        return _star_tracker.intSet_lower_bound(self, x)

    def upper_bound(self, x):
        return _star_tracker.intSet_upper_bound(self, x)

    def equal_range(self, x):
        return _star_tracker.intSet_equal_range(self, x)

    def insert(self, __x):
        return _star_tracker.intSet_insert(self, __x)
    __swig_destroy__ = _star_tracker.delete_intSet
    __del__ = lambda self: None
intSet_swigregister = _star_tracker.intSet_swigregister
intSet_swigregister(intSet)

class ConstCharVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ConstCharVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ConstCharVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _star_tracker.ConstCharVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _star_tracker.ConstCharVector___nonzero__(self)

    def __bool__(self):
        return _star_tracker.ConstCharVector___bool__(self)

    def __len__(self):
        return _star_tracker.ConstCharVector___len__(self)

    def __getslice__(self, i, j):
        return _star_tracker.ConstCharVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _star_tracker.ConstCharVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _star_tracker.ConstCharVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _star_tracker.ConstCharVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _star_tracker.ConstCharVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _star_tracker.ConstCharVector___setitem__(self, *args)

    def pop(self):
        return _star_tracker.ConstCharVector_pop(self)

    def append(self, x):
        return _star_tracker.ConstCharVector_append(self, x)

    def empty(self):
        return _star_tracker.ConstCharVector_empty(self)

    def size(self):
        return _star_tracker.ConstCharVector_size(self)

    def swap(self, v):
        return _star_tracker.ConstCharVector_swap(self, v)

    def begin(self):
        return _star_tracker.ConstCharVector_begin(self)

    def end(self):
        return _star_tracker.ConstCharVector_end(self)

    def rbegin(self):
        return _star_tracker.ConstCharVector_rbegin(self)

    def rend(self):
        return _star_tracker.ConstCharVector_rend(self)

    def clear(self):
        return _star_tracker.ConstCharVector_clear(self)

    def get_allocator(self):
        return _star_tracker.ConstCharVector_get_allocator(self)

    def pop_back(self):
        return _star_tracker.ConstCharVector_pop_back(self)

    def erase(self, *args):
        return _star_tracker.ConstCharVector_erase(self, *args)

    def __init__(self, *args):
        this = _star_tracker.new_ConstCharVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _star_tracker.ConstCharVector_push_back(self, x)

    def front(self):
        return _star_tracker.ConstCharVector_front(self)

    def back(self):
        return _star_tracker.ConstCharVector_back(self)

    def assign(self, n, x):
        return _star_tracker.ConstCharVector_assign(self, n, x)

    def resize(self, *args):
        return _star_tracker.ConstCharVector_resize(self, *args)

    def insert(self, *args):
        return _star_tracker.ConstCharVector_insert(self, *args)

    def reserve(self, n):
        return _star_tracker.ConstCharVector_reserve(self, n)

    def capacity(self):
        return _star_tracker.ConstCharVector_capacity(self)
    __swig_destroy__ = _star_tracker.delete_ConstCharVector
    __del__ = lambda self: None
ConstCharVector_swigregister = _star_tracker.ConstCharVector_swigregister
ConstCharVector_swigregister(ConstCharVector)

class MultiArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MultiArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MultiArray, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _star_tracker.MultiArray_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _star_tracker.MultiArray___nonzero__(self)

    def __bool__(self):
        return _star_tracker.MultiArray___bool__(self)

    def __len__(self):
        return _star_tracker.MultiArray___len__(self)

    def __getslice__(self, i, j):
        return _star_tracker.MultiArray___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _star_tracker.MultiArray___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _star_tracker.MultiArray___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _star_tracker.MultiArray___delitem__(self, *args)

    def __getitem__(self, *args):
        return _star_tracker.MultiArray___getitem__(self, *args)

    def __setitem__(self, *args):
        return _star_tracker.MultiArray___setitem__(self, *args)

    def pop(self):
        return _star_tracker.MultiArray_pop(self)

    def append(self, x):
        return _star_tracker.MultiArray_append(self, x)

    def empty(self):
        return _star_tracker.MultiArray_empty(self)

    def size(self):
        return _star_tracker.MultiArray_size(self)

    def swap(self, v):
        return _star_tracker.MultiArray_swap(self, v)

    def begin(self):
        return _star_tracker.MultiArray_begin(self)

    def end(self):
        return _star_tracker.MultiArray_end(self)

    def rbegin(self):
        return _star_tracker.MultiArray_rbegin(self)

    def rend(self):
        return _star_tracker.MultiArray_rend(self)

    def clear(self):
        return _star_tracker.MultiArray_clear(self)

    def get_allocator(self):
        return _star_tracker.MultiArray_get_allocator(self)

    def pop_back(self):
        return _star_tracker.MultiArray_pop_back(self)

    def erase(self, *args):
        return _star_tracker.MultiArray_erase(self, *args)

    def __init__(self, *args):
        this = _star_tracker.new_MultiArray(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _star_tracker.MultiArray_push_back(self, x)

    def front(self):
        return _star_tracker.MultiArray_front(self)

    def back(self):
        return _star_tracker.MultiArray_back(self)

    def assign(self, n, x):
        return _star_tracker.MultiArray_assign(self, n, x)

    def resize(self, *args):
        return _star_tracker.MultiArray_resize(self, *args)

    def insert(self, *args):
        return _star_tracker.MultiArray_insert(self, *args)

    def reserve(self, n):
        return _star_tracker.MultiArray_reserve(self, n)

    def capacity(self):
        return _star_tracker.MultiArray_capacity(self)
    __swig_destroy__ = _star_tracker.delete_MultiArray
    __del__ = lambda self: None
MultiArray_swigregister = _star_tracker.MultiArray_swigregister
MultiArray_swigregister(MultiArray)

class SysModel(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SysModel, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SysModel, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _star_tracker.new_SysModel(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _star_tracker.delete_SysModel
    __del__ = lambda self: None

    def SelfInit(self):
        return _star_tracker.SysModel_SelfInit(self)

    def CrossInit(self):
        return _star_tracker.SysModel_CrossInit(self)

    def IntegratedInit(self):
        return _star_tracker.SysModel_IntegratedInit(self)

    def UpdateState(self, CurrentSimNanos):
        return _star_tracker.SysModel_UpdateState(self, CurrentSimNanos)

    def Reset(self, CurrentSimNanos):
        return _star_tracker.SysModel_Reset(self, CurrentSimNanos)
    __swig_setmethods__["ModelTag"] = _star_tracker.SysModel_ModelTag_set
    __swig_getmethods__["ModelTag"] = _star_tracker.SysModel_ModelTag_get
    if _newclass:
        ModelTag = _swig_property(_star_tracker.SysModel_ModelTag_get, _star_tracker.SysModel_ModelTag_set)
    __swig_setmethods__["CallCounts"] = _star_tracker.SysModel_CallCounts_set
    __swig_getmethods__["CallCounts"] = _star_tracker.SysModel_CallCounts_get
    if _newclass:
        CallCounts = _swig_property(_star_tracker.SysModel_CallCounts_get, _star_tracker.SysModel_CallCounts_set)
    __swig_setmethods__["RNGSeed"] = _star_tracker.SysModel_RNGSeed_set
    __swig_getmethods__["RNGSeed"] = _star_tracker.SysModel_RNGSeed_get
    if _newclass:
        RNGSeed = _swig_property(_star_tracker.SysModel_RNGSeed_get, _star_tracker.SysModel_RNGSeed_set)
    __swig_setmethods__["moduleID"] = _star_tracker.SysModel_moduleID_set
    __swig_getmethods__["moduleID"] = _star_tracker.SysModel_moduleID_get
    if _newclass:
        moduleID = _swig_property(_star_tracker.SysModel_moduleID_get, _star_tracker.SysModel_moduleID_set)
SysModel_swigregister = _star_tracker.SysModel_swigregister
SysModel_swigregister(SysModel)

class lightSimProperties(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, lightSimProperties, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, lightSimProperties, name)
    __repr__ = _swig_repr
    __swig_setmethods__["visMagnitude"] = _star_tracker.lightSimProperties_visMagnitude_set
    __swig_getmethods__["visMagnitude"] = _star_tracker.lightSimProperties_visMagnitude_get
    if _newclass:
        visMagnitude = _swig_property(_star_tracker.lightSimProperties_visMagnitude_get, _star_tracker.lightSimProperties_visMagnitude_set)
    __swig_setmethods__["RA"] = _star_tracker.lightSimProperties_RA_set
    __swig_getmethods__["RA"] = _star_tracker.lightSimProperties_RA_get
    if _newclass:
        RA = _swig_property(_star_tracker.lightSimProperties_RA_get, _star_tracker.lightSimProperties_RA_set)
    __swig_setmethods__["Dec"] = _star_tracker.lightSimProperties_Dec_set
    __swig_getmethods__["Dec"] = _star_tracker.lightSimProperties_Dec_get
    if _newclass:
        Dec = _swig_property(_star_tracker.lightSimProperties_Dec_get, _star_tracker.lightSimProperties_Dec_set)

    def __init__(self, *args):
        this = _star_tracker.new_lightSimProperties(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _star_tracker.delete_lightSimProperties
    __del__ = lambda self: None
lightSimProperties_swigregister = _star_tracker.lightSimProperties_swigregister
lightSimProperties_swigregister(lightSimProperties)

class LightingSimulation(SysModel):
    __swig_setmethods__ = {}
    for _s in [SysModel]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, LightingSimulation, name, value)
    __swig_getmethods__ = {}
    for _s in [SysModel]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, LightingSimulation, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _star_tracker.delete_LightingSimulation
    __del__ = lambda self: None

    def SelfInit(self):
        return _star_tracker.LightingSimulation_SelfInit(self)

    def CrossInit(self):
        return _star_tracker.LightingSimulation_CrossInit(self)

    def UpdateState(self, CurrentSimNanos):
        return _star_tracker.LightingSimulation_UpdateState(self, CurrentSimNanos)

    def WriteOutputMessages(self, CurrentClock):
        return _star_tracker.LightingSimulation_WriteOutputMessages(self, CurrentClock)

    def ReadInputs(self):
        return _star_tracker.LightingSimulation_ReadInputs(self)

    def setCBodyParam(self):
        return _star_tracker.LightingSimulation_setCBodyParam(self)

    def setCamParam(self):
        return _star_tracker.LightingSimulation_setCamParam(self)

    def updateLighting(self, CurrentClock):
        return _star_tracker.LightingSimulation_updateLighting(self, CurrentClock)

    def addSpacecraftToModel(self, arg2):
        return _star_tracker.LightingSimulation_addSpacecraftToModel(self, arg2)

    def updateRelativePos(self, cbodyState, scState):
        return _star_tracker.LightingSimulation_updateRelativePos(self, cbodyState, scState)
    __swig_setmethods__["scStateInMsgNames"] = _star_tracker.LightingSimulation_scStateInMsgNames_set
    __swig_getmethods__["scStateInMsgNames"] = _star_tracker.LightingSimulation_scStateInMsgNames_get
    if _newclass:
        scStateInMsgNames = _swig_property(_star_tracker.LightingSimulation_scStateInMsgNames_get, _star_tracker.LightingSimulation_scStateInMsgNames_set)
    __swig_setmethods__["scStateInMsgIds"] = _star_tracker.LightingSimulation_scStateInMsgIds_set
    __swig_getmethods__["scStateInMsgIds"] = _star_tracker.LightingSimulation_scStateInMsgIds_get
    if _newclass:
        scStateInMsgIds = _swig_property(_star_tracker.LightingSimulation_scStateInMsgIds_get, _star_tracker.LightingSimulation_scStateInMsgIds_set)
    __swig_setmethods__["scStates"] = _star_tracker.LightingSimulation_scStates_set
    __swig_getmethods__["scStates"] = _star_tracker.LightingSimulation_scStates_get
    if _newclass:
        scStates = _swig_property(_star_tracker.LightingSimulation_scStates_get, _star_tracker.LightingSimulation_scStates_set)
    __swig_setmethods__["LightSimOutMsgNames"] = _star_tracker.LightingSimulation_LightSimOutMsgNames_set
    __swig_getmethods__["LightSimOutMsgNames"] = _star_tracker.LightingSimulation_LightSimOutMsgNames_get
    if _newclass:
        LightSimOutMsgNames = _swig_property(_star_tracker.LightingSimulation_LightSimOutMsgNames_get, _star_tracker.LightingSimulation_LightSimOutMsgNames_set)
    __swig_setmethods__["LightSimMsgIds"] = _star_tracker.LightingSimulation_LightSimMsgIds_set
    __swig_getmethods__["LightSimMsgIds"] = _star_tracker.LightingSimulation_LightSimMsgIds_get
    if _newclass:
        LightSimMsgIds = _swig_property(_star_tracker.LightingSimulation_LightSimMsgIds_get, _star_tracker.LightingSimulation_LightSimMsgIds_set)
    __swig_setmethods__["cbodyPosInMsgName"] = _star_tracker.LightingSimulation_cbodyPosInMsgName_set
    __swig_getmethods__["cbodyPosInMsgName"] = _star_tracker.LightingSimulation_cbodyPosInMsgName_get
    if _newclass:
        cbodyPosInMsgName = _swig_property(_star_tracker.LightingSimulation_cbodyPosInMsgName_get, _star_tracker.LightingSimulation_cbodyPosInMsgName_set)
    __swig_setmethods__["cbodyPosInMsgId"] = _star_tracker.LightingSimulation_cbodyPosInMsgId_set
    __swig_getmethods__["cbodyPosInMsgId"] = _star_tracker.LightingSimulation_cbodyPosInMsgId_get
    if _newclass:
        cbodyPosInMsgId = _swig_property(_star_tracker.LightingSimulation_cbodyPosInMsgId_get, _star_tracker.LightingSimulation_cbodyPosInMsgId_set)
    __swig_setmethods__["bodyState"] = _star_tracker.LightingSimulation_bodyState_set
    __swig_getmethods__["bodyState"] = _star_tracker.LightingSimulation_bodyState_get
    if _newclass:
        bodyState = _swig_property(_star_tracker.LightingSimulation_bodyState_get, _star_tracker.LightingSimulation_bodyState_set)
    __swig_setmethods__["cb_name"] = _star_tracker.LightingSimulation_cb_name_set
    __swig_getmethods__["cb_name"] = _star_tracker.LightingSimulation_cb_name_get
    if _newclass:
        cb_name = _swig_property(_star_tracker.LightingSimulation_cb_name_get, _star_tracker.LightingSimulation_cb_name_set)
    __swig_setmethods__["cb_albedo"] = _star_tracker.LightingSimulation_cb_albedo_set
    __swig_getmethods__["cb_albedo"] = _star_tracker.LightingSimulation_cb_albedo_get
    if _newclass:
        cb_albedo = _swig_property(_star_tracker.LightingSimulation_cb_albedo_get, _star_tracker.LightingSimulation_cb_albedo_set)
    __swig_setmethods__["cb_radius"] = _star_tracker.LightingSimulation_cb_radius_set
    __swig_getmethods__["cb_radius"] = _star_tracker.LightingSimulation_cb_radius_get
    if _newclass:
        cb_radius = _swig_property(_star_tracker.LightingSimulation_cb_radius_get, _star_tracker.LightingSimulation_cb_radius_set)
    __swig_setmethods__["cb_position"] = _star_tracker.LightingSimulation_cb_position_set
    __swig_getmethods__["cb_position"] = _star_tracker.LightingSimulation_cb_position_get
    if _newclass:
        cb_position = _swig_property(_star_tracker.LightingSimulation_cb_position_get, _star_tracker.LightingSimulation_cb_position_set)
    __swig_setmethods__["obs_position"] = _star_tracker.LightingSimulation_obs_position_set
    __swig_getmethods__["obs_position"] = _star_tracker.LightingSimulation_obs_position_get
    if _newclass:
        obs_position = _swig_property(_star_tracker.LightingSimulation_obs_position_get, _star_tracker.LightingSimulation_obs_position_set)
    __swig_setmethods__["dcm_BN_obs"] = _star_tracker.LightingSimulation_dcm_BN_obs_set
    __swig_getmethods__["dcm_BN_obs"] = _star_tracker.LightingSimulation_dcm_BN_obs_get
    if _newclass:
        dcm_BN_obs = _swig_property(_star_tracker.LightingSimulation_dcm_BN_obs_get, _star_tracker.LightingSimulation_dcm_BN_obs_set)
    __swig_setmethods__["cb_distance"] = _star_tracker.LightingSimulation_cb_distance_set
    __swig_getmethods__["cb_distance"] = _star_tracker.LightingSimulation_cb_distance_get
    if _newclass:
        cb_distance = _swig_property(_star_tracker.LightingSimulation_cb_distance_get, _star_tracker.LightingSimulation_cb_distance_set)
    __swig_setmethods__["obs2cb_position"] = _star_tracker.LightingSimulation_obs2cb_position_set
    __swig_getmethods__["obs2cb_position"] = _star_tracker.LightingSimulation_obs2cb_position_get
    if _newclass:
        obs2cb_position = _swig_property(_star_tracker.LightingSimulation_obs2cb_position_get, _star_tracker.LightingSimulation_obs2cb_position_set)
    __swig_setmethods__["obs2cb_position_body"] = _star_tracker.LightingSimulation_obs2cb_position_body_set
    __swig_getmethods__["obs2cb_position_body"] = _star_tracker.LightingSimulation_obs2cb_position_body_get
    if _newclass:
        obs2cb_position_body = _swig_property(_star_tracker.LightingSimulation_obs2cb_position_body_get, _star_tracker.LightingSimulation_obs2cb_position_body_set)
    __swig_setmethods__["cb2obs_distance"] = _star_tracker.LightingSimulation_cb2obs_distance_set
    __swig_getmethods__["cb2obs_distance"] = _star_tracker.LightingSimulation_cb2obs_distance_get
    if _newclass:
        cb2obs_distance = _swig_property(_star_tracker.LightingSimulation_cb2obs_distance_get, _star_tracker.LightingSimulation_cb2obs_distance_set)
    __swig_setmethods__["vis_magnitude"] = _star_tracker.LightingSimulation_vis_magnitude_set
    __swig_getmethods__["vis_magnitude"] = _star_tracker.LightingSimulation_vis_magnitude_get
    if _newclass:
        vis_magnitude = _swig_property(_star_tracker.LightingSimulation_vis_magnitude_get, _star_tracker.LightingSimulation_vis_magnitude_set)
    __swig_setmethods__["RaDec"] = _star_tracker.LightingSimulation_RaDec_set
    __swig_getmethods__["RaDec"] = _star_tracker.LightingSimulation_RaDec_get
    if _newclass:
        RaDec = _swig_property(_star_tracker.LightingSimulation_RaDec_get, _star_tracker.LightingSimulation_RaDec_set)

    def __init__(self, *args):
        this = _star_tracker.new_LightingSimulation(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
LightingSimulation_swigregister = _star_tracker.LightingSimulation_swigregister
LightingSimulation_swigregister(LightingSimulation)

class lightSimMsg(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, lightSimMsg, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, lightSimMsg, name)
    __repr__ = _swig_repr
    __swig_setmethods__["visMagnitude"] = _star_tracker.lightSimMsg_visMagnitude_set
    __swig_getmethods__["visMagnitude"] = _star_tracker.lightSimMsg_visMagnitude_get
    if _newclass:
        visMagnitude = _swig_property(_star_tracker.lightSimMsg_visMagnitude_get, _star_tracker.lightSimMsg_visMagnitude_set)
    __swig_setmethods__["RA"] = _star_tracker.lightSimMsg_RA_set
    __swig_getmethods__["RA"] = _star_tracker.lightSimMsg_RA_get
    if _newclass:
        RA = _swig_property(_star_tracker.lightSimMsg_RA_get, _star_tracker.lightSimMsg_RA_set)
    __swig_setmethods__["Dec"] = _star_tracker.lightSimMsg_Dec_set
    __swig_getmethods__["Dec"] = _star_tracker.lightSimMsg_Dec_get
    if _newclass:
        Dec = _swig_property(_star_tracker.lightSimMsg_Dec_get, _star_tracker.lightSimMsg_Dec_set)

    def __init__(self, *args):
        this = _star_tracker.new_lightSimMsg(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _star_tracker.delete_lightSimMsg
    __del__ = lambda self: None
lightSimMsg_swigregister = _star_tracker.lightSimMsg_swigregister
lightSimMsg_swigregister(lightSimMsg)

class SCPlusStatesSimMsg(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SCPlusStatesSimMsg, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SCPlusStatesSimMsg, name)
    __repr__ = _swig_repr
    __swig_setmethods__["r_BN_N"] = _star_tracker.SCPlusStatesSimMsg_r_BN_N_set
    __swig_getmethods__["r_BN_N"] = _star_tracker.SCPlusStatesSimMsg_r_BN_N_get
    if _newclass:
        r_BN_N = _swig_property(_star_tracker.SCPlusStatesSimMsg_r_BN_N_get, _star_tracker.SCPlusStatesSimMsg_r_BN_N_set)
    __swig_setmethods__["v_BN_N"] = _star_tracker.SCPlusStatesSimMsg_v_BN_N_set
    __swig_getmethods__["v_BN_N"] = _star_tracker.SCPlusStatesSimMsg_v_BN_N_get
    if _newclass:
        v_BN_N = _swig_property(_star_tracker.SCPlusStatesSimMsg_v_BN_N_get, _star_tracker.SCPlusStatesSimMsg_v_BN_N_set)
    __swig_setmethods__["sigma_BN"] = _star_tracker.SCPlusStatesSimMsg_sigma_BN_set
    __swig_getmethods__["sigma_BN"] = _star_tracker.SCPlusStatesSimMsg_sigma_BN_get
    if _newclass:
        sigma_BN = _swig_property(_star_tracker.SCPlusStatesSimMsg_sigma_BN_get, _star_tracker.SCPlusStatesSimMsg_sigma_BN_set)
    __swig_setmethods__["omega_BN_B"] = _star_tracker.SCPlusStatesSimMsg_omega_BN_B_set
    __swig_getmethods__["omega_BN_B"] = _star_tracker.SCPlusStatesSimMsg_omega_BN_B_get
    if _newclass:
        omega_BN_B = _swig_property(_star_tracker.SCPlusStatesSimMsg_omega_BN_B_get, _star_tracker.SCPlusStatesSimMsg_omega_BN_B_set)
    __swig_setmethods__["dcm_BS"] = _star_tracker.SCPlusStatesSimMsg_dcm_BS_set
    __swig_getmethods__["dcm_BS"] = _star_tracker.SCPlusStatesSimMsg_dcm_BS_get
    if _newclass:
        dcm_BS = _swig_property(_star_tracker.SCPlusStatesSimMsg_dcm_BS_get, _star_tracker.SCPlusStatesSimMsg_dcm_BS_set)
    __swig_setmethods__["TotalAccumDVBdy"] = _star_tracker.SCPlusStatesSimMsg_TotalAccumDVBdy_set
    __swig_getmethods__["TotalAccumDVBdy"] = _star_tracker.SCPlusStatesSimMsg_TotalAccumDVBdy_get
    if _newclass:
        TotalAccumDVBdy = _swig_property(_star_tracker.SCPlusStatesSimMsg_TotalAccumDVBdy_get, _star_tracker.SCPlusStatesSimMsg_TotalAccumDVBdy_set)
    __swig_setmethods__["MRPSwitchCount"] = _star_tracker.SCPlusStatesSimMsg_MRPSwitchCount_set
    __swig_getmethods__["MRPSwitchCount"] = _star_tracker.SCPlusStatesSimMsg_MRPSwitchCount_get
    if _newclass:
        MRPSwitchCount = _swig_property(_star_tracker.SCPlusStatesSimMsg_MRPSwitchCount_get, _star_tracker.SCPlusStatesSimMsg_MRPSwitchCount_set)

    def __init__(self, *args):
        this = _star_tracker.new_SCPlusStatesSimMsg(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _star_tracker.delete_SCPlusStatesSimMsg
    __del__ = lambda self: None
SCPlusStatesSimMsg_swigregister = _star_tracker.SCPlusStatesSimMsg_swigregister
SCPlusStatesSimMsg_swigregister(SCPlusStatesSimMsg)

MAX_BODY_NAME_LENGTH = _star_tracker.MAX_BODY_NAME_LENGTH
class SpicePlanetStateSimMsg(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SpicePlanetStateSimMsg, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SpicePlanetStateSimMsg, name)
    __repr__ = _swig_repr
    __swig_setmethods__["J2000Current"] = _star_tracker.SpicePlanetStateSimMsg_J2000Current_set
    __swig_getmethods__["J2000Current"] = _star_tracker.SpicePlanetStateSimMsg_J2000Current_get
    if _newclass:
        J2000Current = _swig_property(_star_tracker.SpicePlanetStateSimMsg_J2000Current_get, _star_tracker.SpicePlanetStateSimMsg_J2000Current_set)
    __swig_setmethods__["PositionVector"] = _star_tracker.SpicePlanetStateSimMsg_PositionVector_set
    __swig_getmethods__["PositionVector"] = _star_tracker.SpicePlanetStateSimMsg_PositionVector_get
    if _newclass:
        PositionVector = _swig_property(_star_tracker.SpicePlanetStateSimMsg_PositionVector_get, _star_tracker.SpicePlanetStateSimMsg_PositionVector_set)
    __swig_setmethods__["VelocityVector"] = _star_tracker.SpicePlanetStateSimMsg_VelocityVector_set
    __swig_getmethods__["VelocityVector"] = _star_tracker.SpicePlanetStateSimMsg_VelocityVector_get
    if _newclass:
        VelocityVector = _swig_property(_star_tracker.SpicePlanetStateSimMsg_VelocityVector_get, _star_tracker.SpicePlanetStateSimMsg_VelocityVector_set)
    __swig_setmethods__["J20002Pfix"] = _star_tracker.SpicePlanetStateSimMsg_J20002Pfix_set
    __swig_getmethods__["J20002Pfix"] = _star_tracker.SpicePlanetStateSimMsg_J20002Pfix_get
    if _newclass:
        J20002Pfix = _swig_property(_star_tracker.SpicePlanetStateSimMsg_J20002Pfix_get, _star_tracker.SpicePlanetStateSimMsg_J20002Pfix_set)
    __swig_setmethods__["J20002Pfix_dot"] = _star_tracker.SpicePlanetStateSimMsg_J20002Pfix_dot_set
    __swig_getmethods__["J20002Pfix_dot"] = _star_tracker.SpicePlanetStateSimMsg_J20002Pfix_dot_get
    if _newclass:
        J20002Pfix_dot = _swig_property(_star_tracker.SpicePlanetStateSimMsg_J20002Pfix_dot_get, _star_tracker.SpicePlanetStateSimMsg_J20002Pfix_dot_set)
    __swig_setmethods__["computeOrient"] = _star_tracker.SpicePlanetStateSimMsg_computeOrient_set
    __swig_getmethods__["computeOrient"] = _star_tracker.SpicePlanetStateSimMsg_computeOrient_get
    if _newclass:
        computeOrient = _swig_property(_star_tracker.SpicePlanetStateSimMsg_computeOrient_get, _star_tracker.SpicePlanetStateSimMsg_computeOrient_set)
    __swig_setmethods__["PlanetName"] = _star_tracker.SpicePlanetStateSimMsg_PlanetName_set
    __swig_getmethods__["PlanetName"] = _star_tracker.SpicePlanetStateSimMsg_PlanetName_get
    if _newclass:
        PlanetName = _swig_property(_star_tracker.SpicePlanetStateSimMsg_PlanetName_get, _star_tracker.SpicePlanetStateSimMsg_PlanetName_set)

    def __init__(self, *args):
        this = _star_tracker.new_SpicePlanetStateSimMsg(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _star_tracker.delete_SpicePlanetStateSimMsg
    __del__ = lambda self: None
SpicePlanetStateSimMsg_swigregister = _star_tracker.SpicePlanetStateSimMsg_swigregister
SpicePlanetStateSimMsg_swigregister(SpicePlanetStateSimMsg)

sizeof_lightSimMsg = _star_tracker.sizeof_lightSimMsg

import sys
protectAllClasses(sys.modules[__name__])

# This file is compatible with both classic and new-style classes.


