function A_hat_I_deriv_z_input = A_hat_I_deriv_z(x_ob,x_sc,y_ob,y_sc,z_ob,z_sc)
%A_HAT_I_DERIV_Z
%    A_HAT_I_DERIV_Z_INPUT = A_HAT_I_DERIV_Z(X_OB,X_SC,Y_OB,Y_SC,Z_OB,Z_SC)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    23-Oct-2017 12:02:33

t2 = conj(z_ob);
t3 = conj(z_sc);
t4 = t2-t3;
t5 = conj(x_ob);
t6 = conj(x_sc);
t7 = t5-t6;
t8 = abs(t7);
t12 = conj(y_ob);
t13 = conj(y_sc);
t14 = t12-t13;
t9 = abs(t14);
t10 = abs(t4);
t11 = sign(t4);
t15 = t8.^2;
t16 = t9.^2;
t17 = t10.^2;
t18 = t15+t16+t17;
t19 = 1.0./t18.^(3.0./2.0);
A_hat_I_deriv_z_input = [t7.*t10.*t11.*t19;t10.*t11.*t14.*t19;-1.0./sqrt(t18)+t4.*t10.*t11.*t19];
