function MM_deriv_y_input = MM_deriv_y(Dx,Dy,FoL,Kx,Ky,RA,dec,twist,x_ob,x_sc,y_ob,y_sc,z_ob,z_sc)
%MM_DERIV_Y
%    MM_DERIV_Y_INPUT = MM_DERIV_Y(DX,DY,FOL,KX,KY,RA,DEC,TWIST,X_OB,X_SC,Y_OB,Y_SC,Z_OB,Z_SC)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    23-Oct-2017 15:52:31

t2 = conj(x_ob);
t3 = conj(x_sc);
t4 = t2-t3;
t5 = abs(t4);
t12 = conj(y_ob);
t13 = conj(y_sc);
t14 = t12-t13;
t6 = abs(t14);
t8 = conj(z_ob);
t9 = conj(z_sc);
t10 = t8-t9;
t7 = abs(t10);
t11 = t5.^2;
t15 = t6.^2;
t16 = t7.^2;
t17 = t11+t15+t16;
t18 = 1.0./sqrt(t17);
t19 = cos(dec);
t20 = cos(twist);
t21 = sin(dec);
t22 = sin(twist);
t23 = sin(RA);
t24 = t20.*t23;
t25 = cos(RA);
t29 = t21.*t22.*t25;
t26 = t24-t29;
t27 = sign(t14);
t28 = 1.0./t17.^(3.0./2.0);
t30 = t22.*t23;
t31 = t20.*t21.*t25;
t32 = t30+t31;
t33 = t4.*t18.*t21;
t34 = t10.*t18.*t19.*t20;
t35 = t14.*t18.*t19.*t22;
t36 = t33+t34+t35;
t37 = 1.0./t36;
t38 = t20.*t25;
t39 = t21.*t22.*t23;
t40 = t38+t39;
t41 = t22.*t25;
t42 = t41-t20.*t21.*t23;
t43 = 1.0./t36.^2;
t44 = t4.*t6.*t21.*t27.*t28;
t45 = t6.*t10.*t19.*t20.*t27.*t28;
t46 = t6.*t14.*t19.*t22.*t27.*t28;
t47 = t44+t45+t46-t18.*t19.*t22;
MM_deriv_y_input = [-Dx.*FoL.*Kx.*t37.*(t18.*t26-t6.*t14.*t26.*t27.*t28+t6.*t10.*t27.*t28.*t32-t4.*t6.*t19.*t25.*t27.*t28)-Dx.*FoL.*Kx.*t43.*t47.*(t14.*t18.*t26-t10.*t18.*t32+t4.*t18.*t19.*t25);-Dy.*FoL.*Ky.*t37.*(t18.*t40+t6.*t10.*t27.*t28.*t42-t6.*t14.*t27.*t28.*t40+t4.*t6.*t19.*t23.*t27.*t28)+Dy.*FoL.*Ky.*t43.*t47.*(t10.*t18.*t42-t14.*t18.*t40+t4.*t18.*t19.*t23)];
