function pl_deriv_x_input = pl_deriv_x(Dx,Dy,FoL,Kx,Ky,RA,dec,twist,x_ob,x_sc,y_ob,y_sc,z_ob,z_sc)
%PL_DERIV_X
%    PL_DERIV_X_INPUT = PL_DERIV_X(DX,DY,FOL,KX,KY,RA,DEC,TWIST,X_OB,X_SC,Y_OB,Y_SC,Z_OB,Z_SC)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    23-Oct-2017 16:57:07

t2 = conj(x_ob);
t3 = conj(x_sc);
t4 = t2-t3;
t5 = abs(t4);
t12 = conj(y_ob);
t13 = conj(y_sc);
t14 = t12-t13;
t6 = abs(t14);
t8 = conj(z_ob);
t9 = conj(z_sc);
t10 = t8-t9;
t7 = abs(t10);
t11 = t5.^2;
t15 = t6.^2;
t16 = t7.^2;
t17 = t11+t15+t16;
t18 = 1.0./sqrt(t17);
t19 = cos(dec);
t20 = cos(twist);
t21 = cos(RA);
t22 = sin(dec);
t23 = sin(twist);
t24 = sign(t4);
t25 = sin(RA);
t26 = 1.0./t17.^(3.0./2.0);
t27 = t20.*t25;
t28 = t27-t21.*t22.*t23;
t29 = t23.*t25;
t30 = t20.*t21.*t22;
t31 = t29+t30;
t32 = t4.*t18.*t22;
t33 = t10.*t18.*t19.*t20;
t34 = t14.*t18.*t19.*t23;
t35 = t32+t33+t34;
t36 = 1.0./t35;
t37 = t20.*t21;
t38 = t22.*t23.*t25;
t39 = t37+t38;
t40 = t21.*t23;
t41 = t40-t20.*t22.*t25;
t42 = 1.0./t35.^2;
t43 = t4.*t5.*t22.*t24.*t26;
t44 = t5.*t10.*t19.*t20.*t24.*t26;
t45 = t5.*t14.*t19.*t23.*t24.*t26;
t46 = t43+t44+t45-t18.*t22;
pl_deriv_x_input = [-Dx.*FoL.*Kx.*t36.*(t18.*t19.*t21+t5.*t10.*t24.*t26.*t31-t5.*t14.*t24.*t26.*t28-t4.*t5.*t19.*t21.*t24.*t26)-Dx.*FoL.*Kx.*t42.*t46.*(-t10.*t18.*t31+t14.*t18.*t28+t4.*t18.*t19.*t21);Dy.*FoL.*Ky.*t36.*(t18.*t19.*t25-t5.*t10.*t24.*t26.*t41+t5.*t14.*t24.*t26.*t39-t4.*t5.*t19.*t24.*t25.*t26)+Dy.*FoL.*Ky.*t42.*t46.*(t10.*t18.*t41-t14.*t18.*t39+t4.*t18.*t19.*t25)];
